#!/usr/bin/env bash
# Type-check the bar's QML the way quickshell will actually see it.
#
# The sources in modules/home/wayland/quickshell/qml are not lintable on their
# own: Config.qml is generated by Nix and is not among them, and the singleton
# needs a qmldir that the runtime never requires. So build the config, lint the
# built copy, and take every import path out of the same nixpkgs the bar runs
# against.
#
# Usage: .claude/skills/quickshell-bar/lint.sh [file.qml ...]
# With no arguments every file in the built config is linted.
set -euo pipefail

host="${QUICKSHELL_LINT_HOST:-framework}"
user="${QUICKSHELL_LINT_USER:-lbischof}"
attr=".#nixosConfigurations.$host.config.home-manager.users.$user"

cd "$(git rev-parse --show-toplevel)"

build() { nix build --no-link --print-out-paths "$1"; }

bar="$(build "$attr.programs.quickshell.configs.bar")"
quickshell="$(build "$attr.programs.quickshell.package")"
qtdeclarative="$(build ".#nixosConfigurations.$host.pkgs.qt6.qtdeclarative")"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp -r "$bar"/. "$work"/
chmod -R u+w "$work"
# qmllint resolves a pragma Singleton only through a qmldir; quickshell finds
# it by directory alone, so the repo has none to copy.
printf 'module bar\nsingleton Config 1.0 Config.qml\n' >"$work/qmldir"

if [ "$#" -gt 0 ]; then
  targets=()
  for f in "$@"; do targets+=("$work/$(basename "$f")"); done
else
  targets=("$work"/*.qml)
fi

# Both -I paths are load-bearing: drop either and every type fails to resolve,
# burying the real findings under hundreds of import warnings.
"$qtdeclarative/bin/qmllint" \
  -I "$work" \
  -I "$qtdeclarative/lib/qt-6/qml" \
  -I "$quickshell/lib/qt-6/qml" \
  "${targets[@]}"
